//GET /api/articles?populate[testDz][on][test.test-compo][fields][0]=testString&populate[testDz][on][test.test-compo][populate]=*&populate[testDz][on][test.test-compo2][fields][0]=testInt
GET https://admin.icorepay.io/api/homepage

//GET http://localhost:1337/api/home-page?populate[0]=hero&populate[1]=section1.cards&populate[2]=section2.usps&populate[3]=section3